### ISSUE TITLE
Error Logging Interceptor

### ISSUE THREAD

**Issue by jordanpowell88** [nestjs-addons/in-memory-db#115]
**Is your feature request related to a problem? Please describe.**
After working on creating the delay interceptor I got to thinking it might be valuable to have an error handling interceptor. 

**Describe the solution you'd like**
It could be configurable to log all requests, or just errors. It could be scoped globally across the entire app or potentially scoped by feature.

**Describe alternatives you've considered**
If we don't feel like this is something valuable for consumers we could just let them create their own custom logging interceptors themselves with nestjs

**Additional context**

**Comment by wesleygrimes** [comment]
Moving over to the mono-repo. Can reopen there. https://github.com/nestjs-addons/platform
