### ISSUE TITLE
Feature: Ability to set a simulated delay on responses

### ISSUE THREAD

**Issue by wesleygrimes** [nestjs-addons/in-memory-db#12]
What does everyone think about having an option that is passed in the to-be-created config for the `InMemoryDBModule` to set a delay in ms on responses to simulate a real backend server that talks to a DB?

A large use case for this package will be for prototyping, and this seems to be a common need.

**Comment by jordanpowell88** [comment]
@wesleygrimes I like this idea as it seams inline with the purpose of the InMemoryDbModule in creating a quick and easy prototype

**Comment by wesleygrimes** [comment]
Awesome. I know @cmwhited was working on a bit for the forRoot config as well. Let’s see where he is at with it. Seems like we need to get the config object implemented first and merged, then move on to implemented the delay piece. I like where you are headed with the commit though Jordan!

**Comment by wesleygrimes** [comment]
@jordanpowell88 I will assign this to you, but also creating an issue for the async crud versions that we need to work on first, before implementing this.

**Comment by cmwhited** [comment]
@nestjs-addons/collaborators love this idea. I think once we get the initial functionality out, another good use-case for this would be to have the delay be random. Like a delay between 500ms - 10,000ms. I think that would make prototyping very powerful as not all calls will have the save response time. Thoughts?

**Comment by wesleygrimes** [comment]
Yup, that's a great one @cmwhited! Random delay is a great idea to make sure you're frontend can handle it. Very common use case.

**Comment by jordanpowell88** [comment]
Great idea @cmwhited !

**Comment by wesleygrimes** [comment]
Just implement on the `async` methods

**Comment by wesleygrimes** [comment]
Moving over to the mono-repo. Can reopen there. https://github.com/nestjs-addons/platform
