### ISSUE TITLE
Error while using async methods

### ISSUE THREAD

**Issue by santoshyadavdev** [nestjs-addons/in-memory-db#144]
**Describe the bug**

**To Reproduce**
1.  Refer  https://github.com/santoshyadav198613/nest-in-memory-demo
2. run npm run build
3. you will get error "src/employee/employee.controller.ts:10:5 - error TS2742: The inferred type of 'GetEmployee' cannot be named without a reference to '@nestjs-addons/in-memory-db/node_modules/rxjs'. This is likely not portable. A type annotation is necessary."

**Expected behavior**
When we try to use async methods we get below errors
The inferred type of 'GetEmployee' cannot be named without a reference to '@nestjs-addons/in-memory-db/node_modules/rxjs'. This is likely not portable. A type annotation is necessary

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DominikPieper** [comment]
What I tried yet: The dependencies are peerDependencies but e.g rxjs are comes withins in-memory-dbs node_modules. If I just delete the rxjs version in node_modules/... In-memory-db/node_modules it works without complaining about different rxjs libs

**Comment by wesleygrimes** [comment]
Closing as resolved with version 2
