### ISSUE TITLE
Feature: Put plumbing in for config to be passed in forRoot

### ISSUE THREAD

**Issue by wesleygrimes** [nestjs-addons/in-memory-db#18]

**Comment by wesleygrimes** [comment]
We have several other features pending this issue getting resolved. 

Open to PRs to help get this implemented. 

@cmwhited @jordanpowell88 was any progress made on this?

**Comment by cmwhited** [comment]
@wesleygrimes, i should have time here soon to get some work on this. even if it just the basic plumbing.

**Comment by wesleygrimes** [comment]
That’s great news! Let me know if I can assist in anyway. Once we get the plumbing in for this a lot of features can start flowing. No pun intended 😂🤣

**Comment by wesleygrimes** [comment]
Hey @cmwhited, @wescopeland had time to get this going for us. It's basic via `forRoot` but it's a great start. Looking forward to your feedback on the `forFeature` implementation down the road.

Thanks everyone for helping out!
