### ISSUE TITLE
Feature: Allow a configurable ID key

### ISSUE THREAD

**Issue by wescopeland** [nestjs-addons/in-memory-db#19]
**Is your feature request related to a problem? Please describe.**
When used to help mock existing APIs/service contracts, the ID key will not always be `id`. For example, we may have a list of users with an ID key of `userId`.

**Describe the solution you'd like**
Allow a configurable ID key. This may require the user-defined interface to not extend `InMemoryDBEntity`.

If you're open to it, I don't mind hacking away at this and opening a PR :-)

**Comment by cmwhited** [comment]
@wescopeland this was something I was thinking about as well. Right now, the `id` is expected to be `id` and also expected to be a `number`. I was considering of going a similar route as [@ngrx/entity](https://ngrx.io/guide/entity) where you can define your `id` field from your entity. If you wanted to give it a go, I don't see any issue with that. @wesleygrimes, thoughts?

**Comment by wesleygrimes** [comment]
Great idea... I have always had this in the back of my mind as something needed. Once we get the forRoot and forFeature config object nailed down, we could add the ability to define the string name of the ID field and then access using some javascript magic like “myRecord[‘userId’]”.

We would then potentially create a private method to get the name of the id field and use it in each of the crud methods. 

The other option is like @cmwhited mentioned where we have a “selectId” method that is defined in the config and it returns the id field. Not as much of a fan of this option as I’m trying to keep this module and simple as humanly possible. 

What do y’all think?

**Comment by wescopeland** [comment]
+1 to IDs being `number | string`.

Great idea with using `forFeature()` to handle this. Something like this maybe?:

```
imports: [
  InMemoryDBModule.forFeature('users', {
    idKey: 'userId'
  })
]
```

This does suggest we'll need a separate module for every in-memory entity type that has a different idKey. Maybe both suggested approaches are good just depending on how the dev wants to architect their mock?

**Comment by wesleygrimes** [comment]
I think we need a different module anyways, so this is great. I like the solution. And by giving it a name we use that as a key in the factory to retrieve the correct instance from DI.

**Comment by wesleygrimes** [comment]
Now that #21 has landed, I'd say let's start by implementing this in the `forRoot` way. I will assign this to you @wescopeland for when you have time.

**Comment by wescopeland** [comment]
Not a problem, I might be able to get around to this as early as tomorrow.

**Comment by kerf007** [comment]
Hello, any updates the feature?

**Comment by wesleygrimes** [comment]
> Hello, any updates the feature?

Will be focusing on this in the next release

**Comment by wesleygrimes** [comment]
Moving over to the mono-repo. Can reopen there. https://github.com/nestjs-addons/platform
