### ISSUE TITLE
Feature: Allow ids of type string

### ISSUE THREAD

**Issue by wescopeland** [nestjs-addons/in-memory-db#29]
**Is your feature request related to a problem? Please describe.**
Right now, ids are statically typed to `number`. In reality, it's possible a back-end we're mocking against could be using randomly-generated `string` ids.

**Describe the solution you'd like**
Add a prop in `InMemoryDBConfig` like `idType`, which accepts a value of "string" or "number". If "number" (or nothing) is set, behave as-is. If "string" is set, randomly generate a string id on the id key for entities, and store entities in the record map using this alphanumeric string key.

**Additional context**
I already have a prototype of this working locally; I don't mind cleaning up and submitting a PR for this issue.

**Comment by Coly010** [comment]
What is being used to randomly generate the string? Will a hashing algorithm be used or something more along the lines of `uuid/v4`?

My only concern is about possible collisions with the generated strings.

**Comment by wescopeland** [comment]
@Coly010 I was thinking something along the lines of `crypto.randomBytes`.

**Comment by wesleygrimes** [comment]
Per @itayod we will use the generic property type accessor like `T['id']`

**Comment by timdeschryver** [comment]
What about making the `getNextId()` configurable instead of setting `idType` to `string` or `number`? 

We could export some helpers like `getNextNumberId()` and `getNextStringId()` to make it easy to use, but it would allow a custom implementation when needed.

**Comment by jordanpowell88** [comment]
@timdeschryver What would the type for `id` be then?

**Comment by timdeschryver** [comment]
@jordanpowell88 a `string | id`? 
I don't know enough about this library, perhaps this can't be done tho.

**Comment by wesleygrimes** [comment]
Agree @timdeschryver, let's close this one.
