### ISSUE TITLE
Feature: add ng add support

### ISSUE THREAD

**Issue by santoshyadavdev** [nestjs-addons/in-memory-db#30]
Add ng-add support to library:

`ng add` will
* add module to imports on `app.module.ts`
* add package to package.json

**Comment by wesleygrimes** [comment]
This would be fantastic Santosh. For now that think it would be good to add the module to the root App Module. Another feature later on could create an Interface for the developer as well.

**Comment by wesleygrimes** [comment]
Hey @santoshyadav198613 are you able to look at this, this week?

**Comment by santoshyadavdev** [comment]
I am done with installation part, adding to import is in progress

**Comment by wesleygrimes** [comment]
Fantastic!
