### ISSUE TITLE
Feature: Need logo

### ISSUE THREAD

**Issue by wesleygrimes** [nestjs-addons/in-memory-db#54]
We need a high-res, unique logo for our library. We also need one for the entire ORG. I’m open to suggestions. Graphic design is not my cup of tea ☕️

**Comment by jordanpowell88** [comment]
I'd love to work on this if no one else has started @nestjs-addons/collaborators

**Comment by wesleygrimes** [comment]
Was hoping you would!

**Comment by jordanpowell88** [comment]
All you have to do is ask!

**Comment by jordanpowell88** [comment]
![nestjs-addons-01](https://user-images.githubusercontent.com/3605268/64573161-5178a080-d338-11e9-9419-722ddf625195.png)
Thoughts? @nestjs-addons/collaborators

**Comment by cmwhited** [comment]
Alright damn. That is super cool.

**Comment by wesleygrimes** [comment]
I have created a new monorepo (https://github.com/nestjs-addons/nestjs-addons), eventually I would like to use `nx` and migrate all of our addons and plugins into this one repository. That's down the road. 

@jordanpowell88  For now, can you do a Pull Request to it, and add an assets folder and push up the logo that you created there? Would be nice to include png, svg, psd files

**Comment by timdeschryver** [comment]
OK. that's what I call an awesome logo 🤩

**Comment by jordanpowell88** [comment]
I went ahead and close this issue since the logo got merged into the mono repo already
