### ISSUE TITLE
Feature: Add functionality to seed data

### ISSUE THREAD

**Issue by cmwhited** [nestjs-addons/in-memory-db#7]
**Is your feature request related to a problem? Please describe.**
It would be a nice addition, since this lib is used largely for quick prototyping, to be able to seed some initial data of the generic type for the service.

**Describe the solution you'd like**
Create a `seed` method that takes an input: `amount: number` of how many records to seed (could have default value like 10). Method creates this amount of random records to store in memory to seed the service and provide a basic initial set of data.

**Comment by wesleygrimes** [comment]
Interesting idea, in the interim we could add a bulk create method called `createMany` that would take in an array of `T` objects. This is probably a broader need as well.

**Comment by wesleygrimes** [comment]
@cmwhited I can take this one on, so we are thinking about adding `service.seed(10)` and randomly generate records? 

What are your thoughts about using a library like this one? 

https://www.npmjs.com/package/factory.ts

**Comment by cmwhited** [comment]
Yeah that was my thought. Something like `.seed(# of records to seed, default 10)`. That factory lib looks cool. I say go with it.

**Comment by cmwhited** [comment]
And, going back to the `forFeature` & `forRoot` discussion, the # of records could be part of the config so when the service is instantiated, it could seed the records based on the config.
