### ISSUE TITLE
RFC: Auto-generated CrUD controller for each feature module and for root module

### ISSUE THREAD

**Issue by wesleygrimes** [nestjs-addons/in-memory-db#73]
### Problem

While not a problem per se, a common use case is to stand up a prototype backend. This requires the developer to create a `Controller` that will call `InMemoryDBService` behind the scenes. What if we generated this for them?

### Possible Solutions

Create a controller with crud operations that call the `async` versions of each method. We would generate a controller using a factory for each `forFeature` module that is registered as well as `forRoot` modules. The route prefix would be the feature name if `forFeature` and a more generic name if only `forRoot` provided.

**Comment by jordanpowell88** [comment]
I like this idea!

**Comment by itayod** [comment]
after giving it another thought, I suggest we will supply a "base" controller instead of generating one with factory for two main reasons:
1. usually each controller has its own unique decorators and metadata.
2. replace implementation comes more naturally to most of the programmers when using extend.

**Comment by wesleygrimes** [comment]
> after giving it another thought, I suggest we will supply a "base" controller instead of generating one with factory for two main reasons:
> 
> 1. usually each controller has its own unique decorators and metadata.
> 2. replace implementation comes more naturally to most of the programmers when using extend.

I agree. This is a much better solution. And developers can eventually drop the extends off if they want to make it a real controller.
