### ISSUE TITLE
RFC: utilize bazel for build

### ISSUE THREAD

**Issue by cmwhited** [nestjs-addons/in-memory-db#75]
### Description
[Bazel](https://docs.bazel.build/versions/master/bazel-overview.html) is a build and test platform that is incredibly powerful and fast.
This RFC is to convert the builds and tests kicked off by the GitHub actions over to utilize bazel and leverage its power.

**Comment by wesleygrimes** [comment]
I'm good with exploring this avenue. Can you submit a PR that reflects this? Using GitHub Actions

**Comment by cmwhited** [comment]
Absolutely. On it.

**Comment by wesleygrimes** [comment]
Closing this in favor of moving to nx
